x = input('Digite um numero inteiro: ')
y = input('Digite outro numero inteiro: ')
z = input('Digite um numero real: ')
produto = (2 * int(x)) * (int(y)/2)
soma = (int(x) * 3) + float(z)
cubo = float(z) * float(z) * float(z)
print("O produto é: " + str(produto))
print("A soma é: " + str(soma))
print("O cubo é: " + str(cubo))